name: 'Supabase Tests'
description: 'Runs Supabase database tests and migrations'

runs:
  using: 'composite'
  steps:
    - name: Install Supabase CLI
      run: |
        curl -fsSL https://supabase.com/install.sh | sh
        echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: Start Supabase
      run: supabase start
      shell: bash
      continue-on-error: true

    - name: Run database migrations
      run: supabase db reset --local
      shell: bash
      continue-on-error: true

    - name: Generate Supabase types
      run: npm run supabase:gen-types
      shell: bash
      continue-on-error: true
