name: 'Code Quality Check'
description: 'Runs type checking, linting, formatting, and tests with CI-optimized Biome commands'

inputs:
  run-tests:
    description: 'Whether to run tests'
    required: false
    default: 'true'
  run-build:
    description: 'Whether to run build'
    required: false
    default: 'true'
  supabase-url:
    description: 'Supabase URL for build'
    required: false
    default: 'https://placeholder.supabase.co'
  supabase-key:
    description: 'Supabase anon key for build'
    required: false
    default: 'placeholder-key'

runs:
  using: 'composite'
  steps:
    - name: ðŸ” TypeScript Type Checking
      run: npm run type-check
      shell: bash

    - name: ðŸ§¹ Biome Linting (CI Mode)
      run: npm run lint:ci
      shell: bash

    - name: ðŸŽ¨ Biome Formatting Check (CI Mode)
      run: npm run format:ci
      shell: bash

    - name: ðŸ§ª Run Tests
      if: inputs.run-tests == 'true'
      run: npm run test:run
      shell: bash

    - name: ðŸ—ï¸ Build Application
      if: inputs.run-build == 'true'
      run: npm run build
      shell: bash
      env:
        NODE_ENV: production
        NEXT_PUBLIC_SUPABASE_URL: ${{ inputs.supabase-url }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ inputs.supabase-key }}

    - name: ðŸ“Š Generate Quality Report
      if: always()
      shell: bash
      run: |
        echo "## ðŸ” Code Quality Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### âœ… Completed Checks" >> $GITHUB_STEP_SUMMARY
        echo "- TypeScript type checking" >> $GITHUB_STEP_SUMMARY
        echo "- Biome linting (CI mode)" >> $GITHUB_STEP_SUMMARY
        echo "- Biome formatting (CI mode)" >> $GITHUB_STEP_SUMMARY
        echo "- Tests: ${{ inputs.run-tests }}" >> $GITHUB_STEP_SUMMARY
        echo "- Build: ${{ inputs.run-build }}" >> $GITHUB_STEP_SUMMARY
