#!/bin/bash

# PageForge CI Setup Script
echo "🚀 Setting up PageForge CI/CD..."

echo "📋 Checklist for CI/CD Setup:"
echo ""
echo "✅ 1. Push code to GitHub repository"
echo "   git add . && git commit -m 'Add CI workflows' && git push origin main"
echo ""
echo "🔐 2. Add GitHub Repository Secrets (Settings → Secrets and variables → Actions):"
echo "   Required for deployment:"
echo "   - VERCEL_TOKEN (get from https://vercel.com/account/tokens)"
echo "   - VERCEL_ORG_ID (run: npx vercel link, then check .vercel/project.json)"
echo "   - VERCEL_PROJECT_ID (run: npx vercel link, then check .vercel/project.json)"
echo ""
echo "   Optional for Supabase (if using real data):"
echo "   - NEXT_PUBLIC_SUPABASE_URL"
echo "   - NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo ""
echo "🔧 3. Test locally first:"
echo "   npm run type-check"
echo "   npm run lint"
echo "   npm run format:check"
echo "   npm run build"
echo ""
echo "🎯 4. Available workflows:"
echo "   - .github/workflows/ci.yml - Full CI pipeline (runs on push/PR)"
echo "   - .github/workflows/basic-ci.yml - Basic checks only"
echo "   - .github/workflows/code-quality.yml - Auto-fix code issues"
echo "   - .github/workflows/deploy.yml - Production deployment"
echo ""
echo "⚡ 5. Quick Vercel setup:"
echo "   npx vercel --prod"
echo "   # This will give you the IDs you need for secrets"
echo ""
echo "🔄 6. Merge commands available:"
echo "   npm run merge-to-main    # Interactive merge with safety checks"
echo "   npm run quick-merge      # Fast merge for experienced users"
echo "   ./scripts/merge-to-main.sh  # Direct script execution"
echo ""
echo "✨ Your CI is ready! Push to main/develop to trigger workflows."
