name: Setup Tests

on:
  workflow_dispatch: # Manual trigger for now

jobs:
  setup-tests:
    name: Setup Test Framework
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install test dependencies
        run: |
          npm install --save-dev @testing-library/react @testing-library/jest-dom jest-environment-jsdom

      - name: Create basic test setup
        run: |
          mkdir -p __tests__
          echo 'describe("Basic test", () => { it("should pass", () => { expect(true).toBe(true); }); });' > __tests__/basic.test.js

      - name: Update package.json test script
        run: |
          npm pkg set scripts.test="jest"
